### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by nabil-2** [cajohare/AxionLimits#2]
Hello,

I was looking for a reference for the RBF and UF limits from RBF_UF_Haloscopes.txt but in AxionLimits_Refs.pdf I found only references [35] and [39] for mass ranges of 4.5 to 5.0 µeV and 5.4 to 5.9 µeV respectively, even though the limit data goes up to 20 µeV. Could you provide a reference for this?

Thanks in advance and best regards

Nabil

**Comment by cajohare** [comment]
Dear Nabil,

Sorry for not spotting this issue until now and thanks for pointing this out. I believe the missing references were the following:

UF - https://inspirehep.net/literature/420476
RBF - https://inspirehep.net/literature/283328

They're now added to the Refs file and readme.
